(function criarControladorAnalyticsAI(global){
  "use strict";
  const debug=(evento,dados)=>{if(global.CCO_DEBUG_ANALYTICS_AI===true)console.log(evento,dados);};
  async function preparar(){const inicio=performance.now(),catalogo=await global.CCOAnalyticsAIService.catalogo();global.CCOAIChat.atualizar({catalogo});debug("[CCO AI CONTEXTO]",global.CCOAIChat.contexto);return{catalogo,tempoMs:performance.now()-inicio};}
  async function processar(pergunta){const total=performance.now();debug("[CCO AI PERGUNTA]",pergunta);const contexto=global.CCOAIChat.contextoParaPergunta(pergunta),catalogo=contexto.catalogo||await global.CCOAnalyticsAIService.catalogo(),inicioInterpretacao=performance.now(),plano=global.CCOAIIntencoes.detectarIntencaoCCO(pergunta,{catalogo,contexto}),tempoInterpretacao=performance.now()-inicioInterpretacao;debug("[CCO AI CONTEXTO]",contexto);debug("[CCO AI CONSULTA]",{acao:plano.acaoOriginal,servicos:plano.servicos,periodos:plano.periodos});const inicioConsulta=performance.now(),resultado=await global.CCOAnalyticsConsultas.executar({...plano,intencao:plano.acaoOriginal},catalogo),tempoConsulta=performance.now()-inicioConsulta;const resposta={plano,resultado,tempos:{interpretacaoMs:tempoInterpretacao,consultaMs:tempoConsulta,totalMs:performance.now()-total}};debug("[CCO AI CÁLCULO]",{tipo:resultado.tipo,registrosAgregados:resultado.dados?.length||0});debug("[CCO AI RESPOSTA]",resposta.tempos);return resposta;}
  function disparar(pergunta){const input=document.getElementById("ccoAnalyticsPergunta"),form=document.getElementById("ccoAnalyticsForm");if(!input||!form)return;input.value=pergunta;form.requestSubmit();}
  async function inicializarContexto(){const{catalogo}=await preparar(),servico=document.getElementById("ccoAIFiltroServico"),ano=document.getElementById("ccoAIFiltroAno"),mes=document.getElementById("ccoAIFiltroMes"),ra=document.getElementById("ccoAIFiltroRA"),turno=document.getElementById("ccoAIFiltroTurno");if(!servico||!ano||!mes)return;servico.innerHTML='<option value="">Todos os serviços</option>'+global.CCOAIConhecimento.servicosValidos.map(item=>`<option value="${item}">${item} — ${global.CCOAIConhecimento.SERVICOS[item].nome}</option>`).join("");const anos=[...new Set(catalogo.map(item=>Number(item.ano)))].sort((a,b)=>b-a);ano.innerHTML=anos.map(item=>`<option value="${item}">${item}</option>`).join("");const recente=[...catalogo].sort((a,b)=>b.ano-a.ano||b.mes-a.mes)[0];ano.value=String(recente?.ano||anos[0]||"");const preencherMeses=()=>{const disponiveis=catalogo.filter(item=>Number(item.ano)===Number(ano.value)).sort((a,b)=>b.mes-a.mes);mes.innerHTML=disponiveis.map(item=>`<option value="${item.mes}">${new Intl.DateTimeFormat("pt-BR",{month:"long"}).format(new Date(2000,item.mes-1,1))}</option>`).join("");if(Number(ano.value)===Number(recente?.ano))mes.value=String(recente?.mes||"");sincronizar();};const sincronizar=()=>{const periodo=catalogo.find(item=>Number(item.ano)===Number(ano.value)&&Number(item.mes)===Number(mes.value));global.CCOAIChat.atualizar({servico:servico.value,ano:Number(ano.value)||null,mes:Number(mes.value)||null,ra:ra.value.trim(),turno:turno.value.trim(),importacaoId:periodo?.importacao_id||null});debug("[CCO AI CONTEXTO]",global.CCOAIChat.contexto);};ano.addEventListener("change",preencherMeses);[servico,mes,ra,turno].forEach(item=>item.addEventListener("change",sincronizar));preencherMeses();document.getElementById("ccoAIResumoExecutivo")?.addEventListener("click",()=>disparar("Prepare um resumo executivo para o período e serviço selecionados."));document.getElementById("ccoAIMostrarCalculo")?.addEventListener("click",()=>disparar("Explique o cálculo da última análise usando a fórmula e os valores oficiais."));}
  global.CCOAnalyticsAIController=Object.freeze({preparar,processar,SYSTEM_PROMPT:global.CCOAIConhecimento.SYSTEM_PROMPT});
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",()=>inicializarContexto().catch(error=>console.warn("[CCO AI CONTEXTO]",error.message)),{once:true}):inicializarContexto().catch(error=>console.warn("[CCO AI CONTEXTO]",error.message));
})(window);
