const fs=require("node:fs"),vm=require("node:vm"),assert=require("node:assert/strict");
const regrasFonte=fs.readFileSync("js/cco-regras-negocio.js","utf8"),serviceFonte=fs.readFileSync("services/painelService.js","utf8"),painelFonte=fs.readFileSync("painel-geral.js","utf8");
function criarBoot(respostas){let consultas=0,sessoes=0;const cliente={from(tabela){assert.equal(tabela,"dias_operacao");const filtros=[];return{select(){return this;},eq(campo,valor){filtros.push([campo,valor]);return this;},async maybeSingle(){consultas++;const resposta=respostas.shift();if(resposta instanceof Error)return{data:null,error:resposta};return{data:resposta??null,error:null};}};}};
  const cacheMemoria=new Map(),window={console,performance,setTimeout,clearTimeout,CCO_DEBUG_AGOSTO:false,CCO_DEBUG_PAINEL_DIAS:false,CCOCache:{chave:(ns,partes)=>`${ns}:${partes.join(":")}`,lembrar:async(_chave,produtor)=>produtor(),invalidar(){},get:chave=>cacheMemoria.get(chave)},CCOSupabase:{getClient:()=>cliente,exigirSessao:async()=>{sessoes++;return{id:"usuario"};}}};window.window=window;const sandbox={window,globalThis:window,console,performance,setTimeout,clearTimeout,AbortController};vm.createContext(sandbox);vm.runInContext(regrasFonte,sandbox);vm.runInContext(serviceFonte,sandbox);return{window,get consultas(){return consultas;},get sessoes(){return sessoes;}};}
(async()=>{
  const linha26={importacao_id:"id-antigo-compativel-com-chave-ano-mes",ano:2026,mes:8,total_dias:26,dados:{}};
  const resultados=[];for(let reload=0;reload<5;reload++){const boot=criarBoot([linha26]),dias=await boot.window.CCOPainelService.diasOperacaoPorPeriodo("id-catalogo-atual",2026,8);assert.equal(dias.total_dias,26);assert.equal(boot.consultas,1);assert.equal(boot.sessoes,1);resultados.push(boot.window.CCO_REGRAS.calcularPrevisto("P1",2026,8));assert.equal(boot.window.CCO_REGRAS.calcularPrevisto("P3",2026,8),12);}
  assert.deepEqual(resultados,[21223,21223,21223,21223,21223]);
  const cacheValido=criarBoot([linha26]);await cacheValido.window.CCOPainelService.diasOperacaoPorPeriodo("x",2026,8);await cacheValido.window.CCOPainelService.diasOperacaoPorPeriodo("x",2026,8);assert.equal(cacheValido.consultas,1);
  const vazio=criarBoot([null,linha26]);assert.equal(await vazio.window.CCOPainelService.diasOperacaoPorPeriodo("x",2026,8),null);assert.equal((await vazio.window.CCOPainelService.diasOperacaoPorPeriodo("x",2026,8)).total_dias,26);assert.equal(vazio.consultas,2,"resultado vazio não pode ser cacheado");
  const retry=criarBoot([new Error("RLS temporária"),linha26]);await assert.rejects(retry.window.CCOPainelService.diasOperacaoPorPeriodo("x",2026,8),/RLS temporária/);assert.equal((await retry.window.CCOPainelService.diasOperacaoPorPeriodo("x",2026,8)).total_dias,26);assert.equal(retry.consultas,2,"Promise rejeitada deve permitir nova tentativa");
  for(const [ano,mes,dias]of[[2026,7,27],[2027,1,25]]){const boot=criarBoot([{importacao_id:null,ano,mes,total_dias:dias,dados:{}}]);await boot.window.CCOPainelService.diasOperacaoPorPeriodo("nova-importacao",ano,mes);assert.equal(boot.window.CCO_REGRAS.calcularPrevisto("P1",ano,mes),21223/26*dias);}
  assert.match(serviceFonte,/\.eq\("ano",Number\(ano\)\)\.eq\("mes",Number\(mes\)\)\.maybeSingle\(\)/);assert.doesNotMatch(serviceFonte,/eq\("importacao_id",id\).*dias_operacao/s);assert.match(painelFonte,/Promise\.all\(\[fontesBase,diasOperacao\]\)/);assert.match(painelFonte,/if\(!dias\)throw new Error/);
  assert.match(painelFonte,/totalDias=temPeriodo&&Number\.isInteger\(estado\.totalDiasMes\)\?estado\.totalDiasMes:null/);
  assert.match(painelFonte,/calcularPrevisto\(servico,totalDias\)/,"previsto deve receber diretamente os dias aguardados, sem efeito colateral global");
  console.log("Painel reload: cinco boots limpos, cache válido, vazio, retry RLS, 27 dias e virada de ano aprovados.");
})().catch(error=>{console.error(error);process.exitCode=1;});
