const fs=require("node:fs"),vm=require("node:vm"),assert=require("node:assert/strict");
const fonte=fs.readFileSync("js/cco-boot-diagnostics.js","utf8");
function ambiente(debug){let tempo=0;const logs=[],storage=new Map(),elementos={filtroKpiAno:{value:"2026"},filtroKpiMes:{value:"07"},filtroKpiDia:{value:""},filtroKpiServico:{value:"P3"}};const window={CCO_DEBUG_BOOT:debug,CCO_PAGE:"kpi",location:{pathname:"/kpi.html"},console:{log:(...a)=>logs.push(a),warn:(...a)=>logs.push(a)},performance:{now:()=>++tempo,mark(){},measure(){},getEntriesByName(){return[];}},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{getElementById:id=>elementos[id]||null},setTimeout,clearTimeout,setInterval,clearInterval};window.window=window;vm.runInNewContext(fonte,{window,console:window.console,MutationObserver:undefined,WeakSet,Map,Set,Proxy,Reflect,Promise,Date,Error,JSON,Object,Number,String,Array,Math,Boolean});return{window,logs};}
const desligado=ambiente(false);assert.equal(desligado.window.CCO_DEBUG_BOOT,false);assert.equal(desligado.logs.length,0);assert.equal(desligado.window.CCOBootDiagnostics.registrarExecucao({funcao:"x"}),null);
const{window}=ambiente(true),D=window.CCOBootDiagnostics;
D.registrarExecucao({funcao:"boot",inicio:1,fim:2,contexto:"mes=07"});D.registrarExecucao({funcao:"boot",inicio:2,fim:3,contexto:"mes=07"});
D.registrarConsulta({tabelaOuRpc:"operacoes",assinatura:"operacoes|P3|2026|07|uuid",inicio:1,fim:3,registros:2});D.registrarConsulta({tabelaOuRpc:"operacoes",assinatura:"operacoes|P3|2026|07|uuid",inicio:3,fim:5,registros:2});
D.registrarListener({elemento:"#filtroKpiMes",evento:"change",nomeHandler:"trocar"});D.registrarListener({elemento:"#filtroKpiMes",evento:"change",nomeHandler:"trocar"});
D.registrarTimer({tipo:"timeout",delay:1800,acao:"REGISTRADO"});D.registrarTimer({tipo:"timeout",delay:1800,acao:"EXECUTADO"});
window.filtroKpiAnoAtual="2026";window.filtroKpiMesAtual="06";window.__CCO_KPI_CONTEXTO_PERIODO__={ano:2026,mes:6,importacaoId:"uuid-junho"};window.__CCO_IMPORTACAO_ATIVA__={importacao_id:"uuid-julho"};D.registrarEstado();
D.registrarGrafico({containerId:"graficoKpi",biblioteca:"ECharts",acao:"CREATE"});D.registrarGrafico({containerId:"graficoKpi",biblioteca:"ECharts",acao:"CREATE"});
const relatorio=D.gerarRelatorio();assert.equal(relatorio.funcoesMaisExecutadas[0].contador,2);assert.equal(relatorio.consultasDuplicadas.length,1);assert.equal(relatorio.listenersDuplicados.length,1);assert.equal(relatorio.timersRegistrados.length,1);assert.equal(relatorio.timersExecutados.length,1);assert.equal(relatorio.estadosDivergentes.length,1);assert.equal(relatorio.graficosDuplicados.length,1);assert.ok(relatorio.performance.totalMs>=0);
for(const pagina of["index","execucao","kpi","historico","dados","analytics-ai"]){const versao=pagina==="index"?"20260811-painel-performance-log-real-v3":"20260806-boot-diagnostics-v1";assert.match(fs.readFileSync(`${pagina}.html`,"utf8"),new RegExp(`js/cco-boot-diagnostics\\.js\\?v=${versao}`));}
assert.doesNotMatch(fonte,/CCOMetricas|P1|P2|P3|P4|P5|P6|P7|P8|P9|P10|P11|P12/,"diagnóstico não deve importar regras de serviço");
console.log("CCO Boot Diagnostics: modo inerte, duplicações, timers, estado, gráficos, relatório e cache-buster aprovados.");
