const fs=require("node:fs"),assert=require("node:assert/strict");
const kpi=fs.readFileSync("kpi.js","utf8"),html=fs.readFileSync("kpi.html","utf8"),renderer=fs.readFileSync("js/cco-graficos-3d.js","utf8");
const chamada=kpi.match(/render\("graficoKpiServicoMensal"[^\n]+/i)?.[0]||"";
assert.ok(chamada,"gráfico Produção mensal deve continuar presente");
assert.match(chamada,/grid:\{top:32,bottom:46\}/,"grid local deve aproveitar a nova altura física");
assert.match(chamada,/labels,\[\{nome:"Executado mensal",valores:consolidado\.executadoMensal,cor:executadoCor\}\]/,"dataset e valores devem permanecer intactos");
assert.match(chamada,/labels\.length===1/,"cenário de um único mês deve continuar suportado");
assert.match(chamada,/cfg=>cfg\.mobile\?"linha":"cilindro"/,"um e vários meses mantêm os renderizadores existentes");
assert.doesNotMatch(chamada,/tooltip:/,"tooltip deve continuar herdado do renderizador compartilhado");
assert.match(renderer,/legend:\{show:series\.length>1\|\|tipo==="rosca"/,"comportamento existente da legenda permanece no renderizador");
assert.match(html,/kpi\.js\?v=20260806-kpi-producao-altura-v2/);
for(const id of["graficoKpiComparativoMensal","graficoKpiServicoDiario","graficoKpiVelocidadeMediaMensal","graficoKpiProdutividadeMensal","graficoKpiServicoIndicadores"])assert.doesNotMatch(kpi,new RegExp(`render\\(\"${id}\"[^\\n]*grid:\\{top:32,bottom:46\\}`),`grid local não pode atingir ${id}`);
console.log("KPI Produção mensal: grid superior isolado, datasets, tooltip, legenda e demais gráficos preservados.");
