const fs=require("node:fs"),assert=require("node:assert/strict");
const css=fs.readFileSync("css/kpi.css","utf8"),kpi=fs.readFileSync("kpi.js","utf8"),html=fs.readFileSync("kpi.html","utf8");
const card=css.match(/body\.kpi-page \.kpi-producao-mensal-card \{[\s\S]*?\n\}/)?.[0]||"",grafico=css.match(/body\.kpi-page \.kpi-producao-mensal-grafico \{[\s\S]*?\n\}/)?.[0]||"",chamada=kpi.match(/render\("graficoKpiServicoMensal"[^\n]+/)?.[0]||"";
assert.match(card,/height: 440px !important/);assert.match(card,/min-height: 440px !important/);assert.match(card,/max-height: 460px !important/);
assert.doesNotMatch(card,/min-height: 520px/);assert.match(card,/grid-template-rows: auto 330px/);assert.match(card,/align-self: start/);assert.match(card,/flex: 0 0 auto/);
assert.match(grafico,/height: 330px !important/);assert.match(grafico,/min-height: 330px !important/);assert.match(grafico,/max-height: 330px !important/);assert.doesNotMatch(grafico,/height: 100%/);
assert.match(chamada,/grid:\{top:32,bottom:46\}/);assert.match(chamada,/labels\.length===1/);assert.match(chamada,/valores:consolidado\.executadoMensal/);assert.doesNotMatch(chamada,/tooltip:/);
assert.match(kpi,/\[KPI PRODUÇÃO ALTURAS\]/);assert.match(kpi,/wrapper:null/);
const indicadores=css.match(/body\.kpi-page \.kpi-indicadores-operacionais-card \{[\s\S]*?\n\}/)?.[0]||"";assert.match(indicadores,/min-height: 520px !important/);
for(const id of["graficoKpiComparativoMensal","graficoKpiServicoDiario","graficoKpiVelocidadeMediaMensal","graficoKpiProdutividadeMensal","graficoKpiServicoIndicadores"])assert.doesNotMatch(kpi,new RegExp(`render\\(\"${id}\"[^\\n]*grid:\\{top:32,bottom:46\\}`));
assert.match(html,/css\/kpi\.css\?v=20260806-kpi-producao-altura-v2/);assert.match(html,/kpi\.js\?v=20260806-kpi-producao-altura-v2/);
console.log("KPI Produção mensal: card 440px, gráfico 330px e grid isolado aprovados.");
