/* CCO | Histórico do novo banco principal. */
(function iniciarHistorico(global){"use strict";global.CCO_PAGE="historico";
  const esc=v=>String(v??"-").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),LOTE=20;let dados=[],visiveis=0;
  const linha=i=>`<tr><td>${i.criado_em?new Date(i.criado_em).toLocaleString("pt-BR"):"-"}</td><td>${esc(i.usuario_nome||i.usuario_email||"Não identificado")}<br><small>${esc(i.usuario_email||"")}</small></td><td>${esc(i.id.slice(0,8))}</td><td>${esc(i.nome_arquivo)}</td><td>${Number(i.linhas_importadas||0).toLocaleString("pt-BR")} RAW / ${Number(i.linhas_rejeitadas||0).toLocaleString("pt-BR")} rejeitadas / ${Number(i.total_abas||0)} abas</td><td><span class="badge ${/^concluida/.test(i.status)?"ok":i.status==="erro"?"danger":"info"}">${esc(i.status)}${i.ativa?" • ativa":""}</span></td><td>${i.ano&&i.mes?`${String(i.mes).padStart(2,"0")}/${i.ano}`:esc((i.periodos||[]).join(", "))}</td></tr>`;
  function renderizar(){const tabela=document.getElementById("tabelaHistorico");if(!tabela)return;tabela.innerHTML=dados.slice(0,visiveis).map(linha).join("")||`<tr><td colspan="7">Nenhuma importação.</td></tr>`;let botao=document.getElementById("carregarMaisHistorico");if(global.CCOEhMobile?.()&&visiveis<dados.length){if(!botao){botao=document.createElement("button");botao.id="carregarMaisHistorico";botao.type="button";botao.className="btn secondary";botao.textContent="Carregar mais";tabela.closest(".table-wrap")?.insertAdjacentElement("afterend",botao);global.CCOMobilePerformance?.registrarListener("historico:carregar-mais",botao,"click",()=>{visiveis=Math.min(dados.length,visiveis+LOTE);renderizar();});}}else botao?.remove();global.CCOMobilePerformance?.fase("CARDS",{linhasHistoricoDOM:Math.min(visiveis,dados.length)});}
  async function carregarInterno(){const tabela=document.getElementById("tabelaHistorico");if(!tabela)return;try{if(!await global.CCOSupabase.exigirSessao())return;const cliente=global.CCOSupabase.getClient(),produtor=()=>global.CCOSupabase.paginar(()=>cliente.from("importacoes").select("id,nome_arquivo,usuario_nome,usuario_email,ano,mes,status,ativa,total_linhas,linhas_importadas,linhas_rejeitadas,total_abas,periodos,criado_em,concluido_em").order("criado_em",{ascending:false}));dados=await(global.CCOMobilePerformance?.dados({pagina:"historico",ano:"todos",mes:"todos",servico:"",importacaoId:"todos"},produtor)||produtor());global.CCOMobilePerformance?.fase("CONSULTA",{registrosRecebidos:dados.length});visiveis=global.CCOEhMobile?.()?Math.min(LOTE,dados.length):dados.length;renderizar();}catch(error){console.error("Erro ao carregar histórico:",error);tabela.innerHTML=`<tr><td colspan="7">Erro ao carregar histórico. Consulte o Console.</td></tr>`;}}
  async function carregar(){return global.CCOBootDiagnostics?global.CCOBootDiagnostics.medir("historico.carregar","historico.js",carregarInterno):carregarInterno();}
  global.carregarHistorico=carregar;
  if(document.readyState==="loading")(global.CCOMobilePerformance?.registrarListener("historico:dom-ready",document,"DOMContentLoaded",carregar,{once:true})||document.addEventListener("DOMContentLoaded",carregar,{once:true}));else carregar();
})(window);
