(function(global){"use strict";
 const S=()=>global.InterrupcaoTrechoService,estado={todos:[],filtrados:[],visiveis:0,charts:{},lazy:new Set()},$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),fmt=n=>Number(n||0).toLocaleString("pt-BR"),top=(obj,n=10)=>Object.entries(obj||{}).sort((a,b)=>b[1]-a[1]).slice(0,n),cores=["#176b46","#20a46b","#43c58a","#f2a93b","#da5d50","#4d7cfe","#7b61ff","#25a4bd","#8a9a91","#b66a9c"];
 function opcoes(id,valores,rotulo){const el=$(id),atual=el.value;el.innerHTML=`<option value="">${rotulo}</option>`+[...new Set(valores.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),"pt-BR",{numeric:true})).map(v=>`<option>${esc(v)}</option>`).join("");el.value=atual;}
 function preencherFiltros(dados){opcoes("filtroAno",dados.map(r=>r.data_ocorrencia?.slice(0,4)),"Todos");opcoes("filtroMes",dados.map(r=>r.mes),"Todos");opcoes("filtroServico",dados.map(r=>r.servico),"Todos");opcoes("filtroDefeito",dados.map(r=>r.tipo_defeito),"Todos");opcoes("filtroRA",dados.map(r=>r.ra),"Todas");opcoes("filtroPerimetro",dados.map(r=>r.perimetro),"Todos");}
 function filtros(){return {ano:$("filtroAno").value,mes:$("filtroMes").value,servico:$("filtroServico").value,defeito:$("filtroDefeito").value,ra:$("filtroRA").value,perimetro:$("filtroPerimetro").value,pesquisa:$("filtroPesquisa").value};}
 function filtrarLocal(){const f=filtros(),t=f.pesquisa.trim().toLowerCase();return estado.todos.filter(r=>(!f.ano||r.data_ocorrencia?.startsWith(f.ano))&&(!f.mes||Number(r.mes)===Number(f.mes))&&(!f.servico||r.servico===f.servico)&&(!f.defeito||r.tipo_defeito===f.defeito)&&(!f.ra||r.ra===f.ra)&&(!f.perimetro||r.perimetro===f.perimetro)&&(!t||[r.rd,r.veiculo,r.mat_motorista,r.descricao].some(v=>String(v||"").toLowerCase().includes(t))));}
 function grafico(id,tipo,obj,{limite=12,indexAxis}={}){const canvas=$(id);if(!canvas||!global.Chart)return;const itens=top(obj,limite),labels=itens.map(x=>x[0]),data=itens.map(x=>x[1]);estado.charts[id]?.destroy();estado.charts[id]=new Chart(canvas,{type:tipo,data:{labels,datasets:[{label:"Ocorrências",data,backgroundColor:tipo==="line"?"rgba(32,164,107,.18)":labels.map((_,i)=>cores[i%cores.length]),borderColor:"#176b46",borderWidth:tipo==="line"?2:0,fill:tipo==="line",tension:.25}]},options:{responsive:true,maintainAspectRatio:false,indexAxis,plugins:{legend:{display:tipo==="doughnut",position:"bottom"}},scales:tipo==="doughnut"?{}:{y:{beginAtZero:true,ticks:{precision:0}}}}});}
 function renderGraficos(c){grafico("graficoDatas","line",Object.fromEntries(Object.entries(c.datas).sort()),{limite:400});grafico("graficoDefeitos","doughnut",c.defeitos,{limite:10});estado.lazy.forEach(nome=>renderLazy(nome,c));}
 function renderLazy(nome,c){if(nome==="veiculos")grafico("graficoVeiculos","bar",c.veiculos,{limite:10,indexAxis:"y"});if(nome==="ras")grafico("graficoRAs","bar",c.ras,{limite:12,indexAxis:"y"});if(nome==="servicos")grafico("graficoServicos","bar",c.servicos,{limite:12});if(nome==="atendimentos")grafico("graficoAtendimentos","doughnut",c.atendimentos,{limite:10});}
 function renderTabela(){const limite=Math.min(estado.visiveis,estado.filtrados.length),dados=estado.filtrados.slice(0,limite);$("tabelaInterrupcoes").innerHTML=dados.length?dados.map(r=>`<tr><td>${esc(r.data_ocorrencia||"—")}</td><td>${esc(r.rd||"—")}</td><td>${esc(r.servico||"—")}</td><td>${esc(r.veiculo||"—")}</td><td>${esc(r.mat_motorista||"—")}</td><td>${esc(r.hora_solicitacao?.slice(0,5)||"—")}</td><td>${esc(r.tipo_defeito||"—")}</td><td>${esc(r.ra||"—")}</td><td>${esc(r.atendimento||"—")}</td><td>${esc(r.hora_deslocamento_socorro?.slice(0,5)||"—")}</td><td>${esc(r.termino_socorro?.slice(0,5)||"—")}</td><td>${esc(r.perimetro||"—")}</td><td title="${esc(r.descricao||"")}">${esc(r.descricao||"—")}</td></tr>`).join(""):`<tr><td colspan="13" class="estado-vazio">Nenhuma ocorrência encontrada.</td></tr>`;$("tabelaResumo").textContent=`Exibindo ${fmt(limite)} de ${fmt(estado.filtrados.length)} registros filtrados.`;$("carregarMais").hidden=limite>=estado.filtrados.length;}
 function render(){estado.filtrados=filtrarLocal();estado.visiveis=Math.min(global.innerWidth<=700?20:100,estado.filtrados.length);const c=S().consolidar(estado.filtrados);$("cardTotal").textContent=fmt(c.total);$("cardVeiculos").textContent=fmt(c.veiculos);$("cardMotoristas").textContent=fmt(c.motoristas);$("cardDefeito").textContent=c.principalDefeito;$("cardTempo").textContent=c.tempoMedio===null?"—":`${Math.round(c.tempoMedio)} min`;$("cardConcluidos").textContent=`${c.concluidos.toFixed(1).replace(".",",")}%`;renderGraficos(c.contagens);renderTabela();$("rankingMotoristas").innerHTML=top(c.contagens.motoristas,10).map(([n,v])=>`<li><strong>${esc(n)}</strong> · ${fmt(v)} ocorrências</li>`).join("")||"<li>Sem dados</li>";const tv=top(c.contagens.veiculos,1)[0],td=top(c.contagens.defeitos,1)[0],tr=top(c.contagens.ras,1)[0],alertas=[];if(tv&&tv[1]>=3)alertas.push(`${tv[0]} concentra ${tv[1]} ocorrências no recorte.`);if(td&&c.total)alertas.push(`${td[0]} representa ${(td[1]/c.total*100).toFixed(1).replace(".",",")}% das ocorrências.`);if(c.tempoMedio>60)alertas.push(`Tempo médio de resposta acima de 60 minutos: ${Math.round(c.tempoMedio)} min.`);$("alertasOperacionais").innerHTML=(alertas.length?alertas:["Nenhum alerta determinístico para o recorte."]).map(a=>`<div class="alerta-item">${esc(a)}</div>`).join("");$("resumoExecutivo").textContent=`O recorte contém ${fmt(c.total)} ocorrências, envolvendo ${fmt(c.veiculos)} veículos. ${td?`O defeito mais frequente é ${td[0]} (${td[1]}). `:""}${tr?`${tr[0]} lidera entre as RAs com ${tr[1]} registros. `:""}A taxa de socorros concluídos é ${c.concluidos.toFixed(1).replace(".",",")}%${c.tempoMedio===null?".":` e a resposta média válida é ${Math.round(c.tempoMedio)} minutos.`}`;}
 async function carregar(){const [meta,dados,perfil]=await Promise.all([S().metadados(),S().consultar({}),global.CCOSupabase.obterPerfilAtual()]);estado.todos=dados;preencherFiltros(dados);const u=meta.ultima;$("statusAtualizacao").textContent=u?new Date(u.criado_em).toLocaleString("pt-BR"):"—";$("statusArquivo").textContent=u?.nome_arquivo||"Nenhuma importação";$("statusTotal").textContent=fmt(meta.total);$("statusMovimento").textContent=`${fmt(u?.linhas_inseridas)} novos · ${fmt(u?.linhas_atualizadas)} atualizados`;const pode=["administrador","operador"].includes(perfil?.perfil)&&perfil?.ativo;$("labelImportar").hidden=!pode;$("perfilAviso").textContent=pode?"Importação incremental habilitada":"Perfil somente leitura";render();}
 function progresso(etapa,atual,total){$("importacaoPainel").hidden=false;$("importacaoEtapa").textContent=etapa;$("importacaoContador").textContent=total?`${fmt(atual)} / ${fmt(total)}`:"";$("importacaoProgresso").value=total?Math.round(atual/total*100):0;}
 async function importar(e){const arquivo=e.target.files?.[0];if(!arquivo)return;try{const r=await S().importar(arquivo,{progresso});$("relatorioImportacao").hidden=false;$("relatorioImportacao").innerHTML=`<h2>Relatório de importação</h2><dl><div><dt>Arquivo</dt><dd>${esc(r.nome_arquivo)}</dd></div><div><dt>Linhas lidas</dt><dd>${fmt(r.total_linhas)}</dd></div><div><dt>Novas</dt><dd>${fmt(r.linhas_inseridas)}</dd></div><div><dt>Atualizadas</dt><dd>${fmt(r.linhas_atualizadas)}</dd></div><div><dt>Ignoradas</dt><dd>${fmt(r.linhas_ignoradas)}</dd></div><div><dt>Rejeitadas</dt><dd>${fmt(r.linhas_rejeitadas)}</dd></div></dl><p>Tempo total: ${(r.tempo_ms/1000).toFixed(1).replace(".",",")} s</p>${r.rejeitadas.length?`<details><summary>Visualizar linhas rejeitadas</summary><ul>${r.rejeitadas.map(x=>`<li>Linha ${x.linha}: ${esc(x.motivo)}</li>`).join("")}</ul></details>`:""}`;await carregar();}catch(err){console.error(err);$("relatorioImportacao").hidden=false;$("relatorioImportacao").textContent=`Falha na importação: ${err.message}`;}finally{e.target.value="";}}
 function eventos(){["filtroAno","filtroMes","filtroServico","filtroDefeito","filtroRA","filtroPerimetro"].forEach(id=>$(id).addEventListener("change",render));$("filtroPesquisa").addEventListener("input",render);$("limparFiltros").addEventListener("click",()=>{document.querySelectorAll(".interrupcao-filtros select,.interrupcao-filtros input").forEach(x=>x.value="");render();});$("carregarMais").addEventListener("click",()=>{estado.visiveis=Math.min(estado.visiveis+(global.innerWidth<=700?20:100),estado.filtrados.length);renderTabela();});$("arquivoInterrupcao").addEventListener("change",importar);const io=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){const n=x.target.dataset.chart;estado.lazy.add(n);renderLazy(n,S().consolidar(estado.filtrados).contagens);io.unobserve(x.target);}}),{rootMargin:"150px"});document.querySelectorAll(".lazy-chart").forEach(x=>io.observe(x));}
 async function init(){try{if(!await global.CCOSupabase.exigirSessao())return;eventos();await carregar();}catch(err){console.error(err);$("tabelaInterrupcoes").innerHTML=`<tr><td colspan="13" class="estado-vazio">Não foi possível carregar a base. Aplique o SQL da funcionalidade e tente novamente.</td></tr>`;}}
 document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
})(window);
