const fs=require("node:fs");
const vm=require("node:vm");
const assert=require("node:assert/strict");

const fonte=fs.readFileSync("painel-geral.js","utf8");
const primeiro=fonte.match(/function primeiroNumeroPositivo\([^)]*\)[\s\S]*?(?=\s*function primeiroNumeroPositivoCCO)/)?.[0];
const consolidar=fonte.match(/function calcularConsolidacaoP9Painel\(operacoesP9,valorAtual=0\)[\s\S]*?(?=\s*function calcularP9PorOperacoes)/)?.[0];
const obter=fonte.match(/function obterAcumuladoRealP9\(linhaPainel,operacoesP9\)[\s\S]*?(?=\s*function calcularAcumuladoP9)/)?.[0];
assert.ok(primeiro&&consolidar&&obter,"funções do P9 devem permanecer rastreáveis");
const contexto={console:{log(){},warn(){},error(){}},window:{}};
vm.createContext(contexto);
vm.runInContext(`const numero=v=>{const n=Number(v);return Number.isFinite(n)?n:0};${primeiro};${consolidar};${obter};window.calcularConsolidacaoP9Painel=calcularConsolidacaoP9Painel;window.obterAcumuladoRealP9=obterAcumuladoRealP9;`,contexto);
const calcular=valores=>contexto.window.calcularConsolidacaoP9Painel(valores.map(qtd_equipe=>({qtd_equipe}))).acumulado;
assert.equal(calcular([1,1,1]),3);
assert.equal(calcular(Array(11).fill(1)),11);
assert.equal(calcular(Array(18).fill(1)),11);
assert.equal(calcular([0.4666667,0.5333333,4.5333333]),0);
assert.equal(calcular([0,-1,-3]),0);
assert.equal(calcular([0,1,1]),2);
assert.equal(contexto.window.obterAcumuladoRealP9({acumulado:4.53},Array(11).fill({qtd_equipe:1})),11);
assert.equal(contexto.window.obterAcumuladoRealP9({acumulado:4.53},[]),4.53);
assert.equal(11*122039.23,1342431.53);
console.log("Painel P9: soma de equipes válidas limitada a 11 aprovada.");
