begin;
create extension if not exists pgcrypto;

create table if not exists public.interrupcoes_importacoes (
  id uuid primary key default gen_random_uuid(), nome_arquivo text not null, hash_arquivo text not null,
  total_linhas integer not null default 0 check(total_linhas>=0), linhas_inseridas integer not null default 0 check(linhas_inseridas>=0),
  linhas_atualizadas integer not null default 0 check(linhas_atualizadas>=0), linhas_ignoradas integer not null default 0 check(linhas_ignoradas>=0),
  linhas_rejeitadas integer not null default 0 check(linhas_rejeitadas>=0), usuario_id uuid not null references auth.users(id),
  criado_em timestamptz not null default now(), status text not null check(status in ('processando','concluida','falhou'))
);
create table if not exists public.interrupcoes_trecho (
  id bigint generated by default as identity primary key, importacao_id uuid not null references public.interrupcoes_importacoes(id) deferrable initially deferred,
  mes smallint check(mes between 1 and 12), data_ocorrencia date not null, servico text, veiculo text not null, rd text, mat_motorista text,
  hora_saida_garagem time, ra text, lat_long text, hora_solicitacao time, tipo_defeito text, atendimento text, veiculo_atendimento text,
  local_saida_socorro text, hora_deslocamento_socorro time, mat_socorrista text, termino_socorro time, acionamento_sesmt text,
  acionamento_perito text, perimetro text, descricao text, chave_registro text not null unique,
  criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create index if not exists interrupcoes_trecho_data_idx on public.interrupcoes_trecho(data_ocorrencia);
create index if not exists interrupcoes_trecho_filtros_idx on public.interrupcoes_trecho(mes,servico,tipo_defeito,ra,perimetro);
create or replace function public.interrupcoes_trecho_atualizado_em() returns trigger language plpgsql set search_path=public as $$ begin new.atualizado_em=now(); return new; end $$;
drop trigger if exists trg_interrupcoes_trecho_atualizado on public.interrupcoes_trecho;
create trigger trg_interrupcoes_trecho_atualizado before update on public.interrupcoes_trecho for each row execute function public.interrupcoes_trecho_atualizado_em();
create or replace function public.pode_importar_interrupcoes() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.perfis_usuario where usuario_id=auth.uid() and ativo and perfil in ('administrador','operador')) $$;
alter table public.interrupcoes_trecho enable row level security; alter table public.interrupcoes_importacoes enable row level security;
drop policy if exists interrupcoes_leitura on public.interrupcoes_trecho; create policy interrupcoes_leitura on public.interrupcoes_trecho for select to authenticated using (exists(select 1 from public.perfis_usuario where usuario_id=auth.uid() and ativo));
drop policy if exists interrupcoes_escrita on public.interrupcoes_trecho; create policy interrupcoes_escrita on public.interrupcoes_trecho for all to authenticated using(public.pode_importar_interrupcoes()) with check(public.pode_importar_interrupcoes());
drop policy if exists interrupcoes_importacoes_leitura on public.interrupcoes_importacoes; create policy interrupcoes_importacoes_leitura on public.interrupcoes_importacoes for select to authenticated using(exists(select 1 from public.perfis_usuario where usuario_id=auth.uid() and ativo));
drop policy if exists interrupcoes_importacoes_escrita on public.interrupcoes_importacoes; create policy interrupcoes_importacoes_escrita on public.interrupcoes_importacoes for insert to authenticated with check(public.pode_importar_interrupcoes() and usuario_id=auth.uid());
drop policy if exists interrupcoes_importacoes_atualizacao on public.interrupcoes_importacoes; create policy interrupcoes_importacoes_atualizacao on public.interrupcoes_importacoes for update to authenticated using(public.pode_importar_interrupcoes() and usuario_id=auth.uid()) with check(public.pode_importar_interrupcoes() and usuario_id=auth.uid());
grant select on public.interrupcoes_trecho,public.interrupcoes_importacoes to authenticated; grant insert,update on public.interrupcoes_trecho,public.interrupcoes_importacoes to authenticated; grant usage,select on sequence public.interrupcoes_trecho_id_seq to authenticated; grant execute on function public.pode_importar_interrupcoes() to authenticated;
commit;
